#!/usr/bin/env python
from __future__ import print_function
import hashlib
import sys

#  hashencrypter.py
#  Created by Blackjack & Blackjack21
#  Reviewed by Alighiero@Technology
#  Used to convert strings to hashes
#  MD5, SHA1, SHA224, SHA256, SHA384, SHA512
#
#  Email: anivsante2@gmail.com
#  Email: alighierotechnology@gmail.com
#
#  Links:
#       https://github.com/MichaelDim02/BlackJack
#       https://github.com/MichaelDim02/BlackJack21

try:
    hash_convert = sys.argv
    string = hash_convert[1]

    def converter():
        print("\nMD5:    ",hashlib.md5(string).hexdigest())
        print("\nSHA1:   ",hashlib.sha1(string).hexdigest())
        print("\nSHA224  ",hashlib.sha224(string).hexdigest())
        print("\nSHA256: ",hashlib.sha256(string).hexdigest())
        print("\nSHA384  ",hashlib.sha384(string).hexdigest())
        print("\nSHA512: ",hashlib.sha512(string).hexdigest())
    converter()
except:
    print("""
     _   _              _     
    | | | |            | |    
    | |_| |  __ _  ___ | |__  
    |  _  | / _` |/ __|| '_ \ 
    | | | || (_| |\__ \| | | |
    \_| |_/ \__,_||___/|_| |_|

    ____  _            _        _            _    
    |  _ \| |          | |      | |          | |   
    | |_) | | __ _  ___| | __   | | __ _  ___| | __
    |  _ <| |/ _` |/ __| |/ /   | |/ _` |/ __| |/ /
    | |_) | | (_| | (__|   < |__| | (_| | (__|   < 
    |____/|_|\__,_|\___|_|\_\____/ \__,_|\___|_|\_\
                                             
    Created by Blackjack & BlackJack21 by Michael Dim                     
    Reviewed and edited by Alighiero@Technology
                                               v03.20

    Usage Mode: python hachblackjack.py [name for convert]
    Example: python hashblackjack.py blackjack
    """)
    sys.exit(1)

