#!/usr/bin/env python
#!/usr/bin/bash

# Created by diegocosta.deb
# E-Mail: alighierotechnology@gmail.com
# Reviewed by ...

from __future__ import print_function
import socket
import os
import sys

if __name__ == '__main__':
    print("""
        .o oOOOOOOOo                                            OOOo 
        Ob.OOOOOOOo  OOOo.      oOOo.                      .adOOOOOOO 
        OboO000000000000.OOo. .oOOOOOo.    OOOo.oOOOOOo..0000000000OO 
        OOP.oOOOOOOOOOOO `POOOOOOOOOOOo.   ``OOOOOOOOOP,OOOOOOOOOOOB' 
        'O'OOOO'     0OOOOooOOOOOOOOOOO' .adOOOOOOOOO'oOOO0    'OOOOo 
        .OOOO'            'OOOOOOOOOOOOOOOOOOOOOOOOOO'            'OO 
        OOOOO                 '0OOOOOOOOOOOOOOOO0`                oOO 
       oOOOOOba.                .adOOOOOOOOOOba               .adOOOOo. 
      oOOOOOOOOOOOOOba.    .adOOOOOOOOOO00OOOOOOOba.     .adOOOOOOOOOOOO 
     OOOOOOOOOOOOOOOOO.OOOOOOOOOOOOOO0`  '0OOOOOOOOOOOOO.OOOOOOOOOOOOOO 
     'OOOO'       'YOoOOOOMOIONODOO''  .   ''OOROAOPOEOOOoOY'     'OOO' 
        Y           'OOOOOOOOOOOOOO: .oOOo. :OOOOOOOOOOO0'         :' 
        :            .oO0OOOOOOOOOOo.OOOOOO.oOOOOOOOOOOOO0         . 
        .            oOOP'0OOOOOOOOoOOOOOOO0oOOOOO0OOOO'OOo 
                     '0o  OOOO'0OOOO0'0OOOOO'OOOOOO'OOO': 
                          `$'  `OOOO' `O'Y ' `OOOO'  o             . 
        .                  .     OP'          : o     . 
                                  : 
    
    
       ______          _   _____                 
       | ___ \        | | /  ___|                
       | |_/ /__  _ __| |_\ `--.  ___ __ _ _ __  
       |  __/ _ \| '__| __|`--. \/ __/ _` | '_ \ 
       | | | (_) | |  | |_/\__/ / (_| (_| | | | |
       \_|  \___/|_|   \__\____/ \___\__,_|_| |_|
     PortScan v20.03 by diegocosta.deb 2019/2020 
    """)

try:
    targetserver = sys.argv[1]
    targetIP = socket.gethostbyname(targetserver)
    print('')

    print('# Target: {} # IP: {}'.format(targetserver, targetIP)) 
    print('')

    print('='*50)
    for port in range(1, 65535):
        client = socket.socket(socket.AF_INET,socket.SOCK_STREAM)
        client.settimeout(0.1)
        code = client.connect_ex((targetserver, port))
    
        if code == 0:
            print("[OPENDOOR] {} on target --> {}:{}".format(port, targetserver,targetIP))
            dbase ='[OPENDOOR] {} -- {}:{}'.format(port, targetserver, targetIP)
            os.system('echo {} >> ~/Public/{}:{}'.format(dbase, targetserver, targetIP))

        else:
	    print("[CLOSEDOOR] {} on target --> {}:{}".format(port, targetserver,targetIP))
except:
    print('--> Command arguments are missing!')
    print('--> Usage: portscan <host name>')
    sys.exit()

print('='*50)

